Par 5/home page standards
DevMentorship/paravina-rebuild pull request #1
Opened 2023-04-16 19:09 UTC by sane4ek1994

2023-04-16 19:27 UTC, andrey-kudinov requested changes
Отличная работа
Посмотри пж в комментариях как сделать код ещё лучше

2023-04-16 19:27 UTC, andrey-kudinov commented on src/components/Standards/Standards.module.css
> +.cards_list {
`cards-list`

2023-04-16 19:27 UTC, andrey-kudinov commented on src/components/Standards/Standards.tsx
> +        <ul className={styles.cards_list}>
`styles['cards-list']`

2023-04-16 19:27 UTC, andrey-kudinov commented on src/components/Standards/Standards.tsx
> +        <ul className={styles.cards_list}>
`styles.cards`

2023-04-16 19:27 UTC, andrey-kudinov commented on src/components/Standards/Standards.tsx
> +  return (
const cards = [{ title: "какой-то title", text: "какой-то text" }, ...]

{cards.map(card => ...)

2023-04-16 19:27 UTC, andrey-kudinov commented on src/components/Standards/Standards.tsx
> +      <div className={styles.standards_wrapper}>
`wrapper`

2023-04-16 19:27 UTC, andrey-kudinov commented on src/components/Standards/Standards.tsx
> +            <p className={styles.card_text}>Это новое качество в стоматологии XXI века</p>
`text`

2023-04-16 19:38 UTC, sane4ek1994 commented on src/components/Standards/Standards.tsx
> +  return (
Не догадался сразу, я исправлю.

2023-04-17 16:18 UTC, andrey-kudinov approved these changes

2023-04-17 16:19 UTC, merged