Tabs component refactor. Adding logic
DevMentorship/paravina-rebuild pull request #2
Opened 2023-04-16 20:26 UTC by Dmitry-Shambarov

2023-04-17 11:08 UTC, andrey-kudinov requested changes
Отличная работа
Посмотри пж в комментариях как можно улучшить код

Так же обрати внимание на доступность - навигацию с клавиатуры
Возможно стоит использовать кнопки или ссылки

2023-04-17 11:08 UTC, andrey-kudinov commented on src/components/Tabs/Tabs.tsx
> +                category: 'stomatology'
думаю можно удалить

2023-04-17 11:08 UTC, andrey-kudinov commented on src/components/Tabs/Tabs.tsx
> +    const filteredServices = services[selectedCategory]?.filter((service) => service.category === selectedCategory) ?? [];
думаю фильтрация не нужна

2023-04-17 11:08 UTC, andrey-kudinov commented on src/components/Tabs/Tabs.tsx
> +                            className={selectedCategory === 'stomatology' ? cn(styles.trigger, styles['trigger--active'])
`className={selectedCategory === 'stomatology' ? cn(styles.trigger, styles['trigger--active']) : styles.trigger}`

`className={cn(styles.trigger, selectedCategory === 'stomatology' && styles['trigger--active'])}`

2023-04-17 11:08 UTC, andrey-kudinov commented on src/components/Tabs/Tabs.tsx
> +                {filteredServices.map((service) => (
`services[selectedCategory].map(...`

2023-04-17 11:08 UTC, andrey-kudinov commented on src/components/Tabs/Tabs.tsx
> +                    <div key={service.id} className={cn(styles.item)}>
`index`

2023-04-17 11:08 UTC, andrey-kudinov commented on src/components/Tabs/Tabs.tsx
> +                id: 1,
думаю можно удалить

2023-04-17 11:08 UTC, andrey-kudinov commented on src/components/Tabs/Tabs.tsx
> +                    <div key={service.id} className={cn(styles.item)}>
`className={styles.item}`

2023-04-17 19:02 UTC, Dmitry-Shambarov commented on src/components/Tabs/Tabs.tsx
> +                category: 'stomatology'
Не совсем понимаю почему мы можем это удалить. Откуда мы будем брать данные в таком случае?

2023-04-19 16:40 UTC, andrey-kudinov approved these changes

2023-04-19 16:40 UTC, merged