Par 37/about page team
DevMentorship/paravina-rebuild pull request #29
Opened 2023-06-05 10:25 UTC by Grec88

2023-06-05 13:01 UTC, andrey-kudinov requested changes
Отличная работа
Посмотри пж несколько комментариев, которые я надеюсь, помогут немного улучшить кодовую базу

2023-06-05 13:01 UTC, andrey-kudinov commented on src/components/Team/Team.tsx
> +export interface IDoctorAbout {
`IDoctor` думаю будет гуд
Лаконично

2023-06-05 13:01 UTC, andrey-kudinov commented on src/pages/doctors/slug.module.css
> +.backBtn {
`.back` думаю будет хорошо

2023-06-05 13:01 UTC, andrey-kudinov commented on src/pages/doctors/[slug].tsx
> +    fallback: 'blocking',
после активной разработки заменим на `false`, чтобы страницы были статически сгенерированы

2023-06-05 13:01 UTC, andrey-kudinov commented on src/pages/doctors/[slug].tsx
> +          alt="prev arrow"
`alt="Назад"`

2023-06-05 13:01 UTC, andrey-kudinov commented on src/pages/doctors/[slug].tsx
> +          src="https://res.cloudinary.com/dkqwi0tah/image/upload/f_auto,q_auto/v1685609956/Paravina-rebuild/arrow_wy5l6k.svg"
В дальнейшем вынесем в конфиг некста префис `https://res.cloudinary.com/dkqwi0tah/image/upload/f_auto,q_auto/v1685609956/Paravina-rebuild`
Чтобы более короткие были адреса картинок

2023-06-08 17:00 UTC, DmitriyAvgustinovich commented
Хорошая работа, все недочеты исправил

2023-06-08 17:00 UTC, DmitriyAvgustinovich approved these changes

2023-06-09 03:52 UTC, oiva-terho approved these changes
Your job looks good for me. 
It would be nice if you'll correct arrows styles too. Images aren't on center. 
![image](https://github.com/DevMentorship/paravina-rebuild/assets/108938295/5bae3559-4e81-4eb6-80a5-fa5b1a287285)
For example it may be: 
.prev,
.next {
  ...
  display: grid;
  place-items: center;
}

2023-06-09 09:09 UTC, andrey-kudinov approved these changes

2023-06-09 09:09 UTC, merged