PAR-29/Price_Page_Tabs
DevMentorship/paravina-rebuild pull request #30
Opened 2023-06-05 12:46 UTC by Grec88

2023-06-08 16:56 UTC, DmitriyAvgustinovich commented
Хорошая работа, отлично!

2023-06-08 16:56 UTC, DmitriyAvgustinovich approved these changes

2023-06-09 03:25 UTC, oiva-terho approved these changes
good job.

2023-06-09 09:07 UTC, andrey-kudinov requested changes
Круто получилось!
Убери пж затемнение на неактивном табе
<img width="653" alt="image" src="https://github.com/DevMentorship/paravina-rebuild/assets/64890665/aa2e650c-44c8-4176-b21b-e8999ffca360">

Также сделай чтобы на мобилке они были во всю ширину и в столбик
А на промежуточных разрешениях был горизонтальный скролл

Спасибо!

2023-06-09 09:08 UTC, andrey-kudinov commented on src/components/AccordionItem/AccordionItem.tsx
> +  tabIndex?: number | undefined;
`tabIndex?: number`

можно просто так

2023-06-12 11:39 UTC, merged