Par 30/header contact us form
DevMentorship/paravina-rebuild pull request #32
Opened 2023-06-05 14:29 UTC by oiva-terho

+ popup as dialog element
+ form with name, phone, note and agreement fields
+ close by button, esc key and background
+ input check and error notification
+ fetch placeholder
+ fetch result success and error messages
+ success and error svg images
+ spinner for loading
+ scroll fix while popup is opened

2023-06-05 16:19 UTC, andrey-kudinov requested changes
Хорошая работа
Посмотри пж комментарии
Так же упрости пж валидацию

2023-06-05 16:19 UTC, andrey-kudinov commented on src/hooks/useScrollBlock.ts
👍

2023-06-05 16:19 UTC, andrey-kudinov commented on src/components/Popup/Popup.module.css
> +  border: none;
Добавь пж скругленные уголки, на `15px`

2023-06-05 16:19 UTC, andrey-kudinov commented on src/components/Popup/Popup.module.css
> +dialog.popup {
На сафари старше 2022 года открывается с глюком этот тег
Модалка появляется сразу при загрузке и её не удаётся закрыть

<img width="1028" alt="image" src="https://github.com/DevMentorship/paravina-rebuild/assets/64890665/f764b3f6-4f15-47b4-932b-c516c1887068">
https://caniuse.com/?search=dialog

Я думаю нам нужен fallback или пока что лучше просто использовать div
Я думаю с текущей поддержкой мы пока не готовы к использованию этого тега (

2023-06-05 16:19 UTC, andrey-kudinov commented on src/components/Popup/Popup.module.css
> +dialog.popup {
Без атрибута open она открыта
<img width="898" alt="image" src="https://github.com/DevMentorship/paravina-rebuild/assets/64890665/7160b725-8f4c-4acb-875f-00a6184e4759">
Я использовал для тестирования сервис browserstack.com

2023-06-05 16:19 UTC, andrey-kudinov commented on src/components/Popup/Popup.module.css
> +  padding: 1.5em;
Для НЕ шрифтовых свойств используй пж px
Для шрифтовых rem
В проекте 1rem = 10px

2023-06-05 16:19 UTC, andrey-kudinov commented on src/components/Popup/Popup.module.css
> +.popup > form > textarea:focus-visible {
👍

2023-06-05 16:19 UTC, andrey-kudinov commented on src/components/Popup/Popup.tsx
> +    });
👍

2023-06-05 16:19 UTC, andrey-kudinov commented on src/components/Popup/Popup.tsx
> +              <a href="/agreement">Согласие с условиями</a>
Здесь не очевидно что это ссылка
Ссылкой может быть только слово `Условия` и оно может быть подчёркнуто как обычная ссылка

2023-06-05 16:19 UTC, andrey-kudinov commented on src/components/Popup/Popup.tsx
> +              <a href="/agreement">Согласие с условиями</a>
![Uploading image.png…]()

2023-06-05 16:19 UTC, andrey-kudinov commented on src/components/Popup/Popup.tsx
> +          <textarea required placeholder="Примечание" name="note" value={note} onChange={handleChange} />
<img width="624" alt="image" src="https://github.com/DevMentorship/paravina-rebuild/assets/64890665/f48bacb3-b86e-4c97-b36b-fd31b4e8fe89">
Примечание не должно быть для нас обязательным
С нашей стороны хорошо сделать меньше препятствий для клиента, но в то же время иметь противовандальную валидацию

2023-06-05 16:19 UTC, andrey-kudinov commented on src/components/Popup/Popup.tsx
> +          <textarea required placeholder="Примечание" name="note" value={note} onChange={handleChange} />
Например скопированный номер из тг не проходит валидацию

2023-06-05 16:19 UTC, andrey-kudinov commented on src/components/Popup/Popup.tsx
> +          <textarea required placeholder="Примечание" name="note" value={note} onChange={handleChange} />
Здесь не отрабатывает кнопка Отправить
![Uploading image.png…]()

2023-06-08 01:18 UTC, oiva-terho commented
@andrey-kudinov Check this solution for Safari, please. I cannot test it. Did it in blind.
I also tried https://github.com/GoogleChrome/dialog-polyfill but it failed dev server for me from the box.

2023-06-08 16:06 UTC, DmitriyAvgustinovich commented on src/components/Popup/Popup.tsx
> +          <textarea required placeholder="Примечание" name="note" value={note} onChange={handleChange} />
При открытом модальном окне на мобильных устройствах скролл все равно присутствует, ios 15.4

2023-06-09 02:16 UTC, oiva-terho commented
@andrey-kudinov changed to divs, it works for me.
@DmitriyAvgustinovich fixed bug for iOS 15.

2023-06-09 09:03 UTC, andrey-kudinov requested changes
Всё хорошо выглядит
Осталось немного
- убери пж черную рамку вокруг textarea
- сделай пж кнопку как остальные на сайте
- обработай пж адаптив

![Uploading image.png…]()

2023-06-20 18:29 UTC, merged