add slider gallery on mobile and popup
DevMentorship/paravina-rebuild pull request #33
Opened 2023-06-05 17:44 UTC by DmitriyAvgustinovich

2023-06-05 18:00 UTC, andrey-kudinov requested changes
Хорошая работа! Посмотри пж несколько комментариев, думаю с ними ты сделаешь код еще лучше

2023-06-05 18:00 UTC, andrey-kudinov commented on src/components/Gallery/Gallery.module.css
> +.swiperSlider {
Я думаю можно из одного слова или если не сложно, используй пж кебаб-кейс (как в ванильном css)

2023-06-05 18:00 UTC, andrey-kudinov commented on src/components/Gallery/Gallery.module.css
>  .img__big {
Здесь не твой код, но смешивать модули и БЭМ плохая практика
У нас уже есть изоляция стилей и их не так много, думаю можно  без БЭМ
Упрости пж нейминг в этой части

2023-06-05 18:00 UTC, andrey-kudinov commented on src/components/Gallery/Gallery.tsx
> +          {/* TODO: fix arrow svg (vertical) */}
Удали плиз коммент, он уже не актуальный благодаря тебе)

2023-06-05 18:00 UTC, andrey-kudinov commented on src/components/Gallery/Gallery.tsx
> +            <Image
Думаю надо на русском делать alt и сообщение для скрин ридеров

2023-06-05 18:00 UTC, andrey-kudinov commented on src/components/GalleryPopup/GalleryPopup.module.css
> +.closeBtn {
close будет достаточно

2023-06-05 18:00 UTC, andrey-kudinov commented on src/components/GalleryPopup/GalleryPopup.tsx
> +            <button className={styles.closeBtn} onClick={isClose}>
Думаю при открытии лучше навести фокус на крестик

2023-06-08 14:15 UTC, pontificust commented on src/components/Gallery/Gallery.module.css
> -.img__big {
Для лучшей читаемости и восприятия кода можно использовать kebab case.

2023-06-08 14:15 UTC, pontificust commented on src/components/Gallery/Gallery.module.css
> +  height: 340px;
![Снимок экрана 2023-06-08 171040](https://github.com/DevMentorship/paravina-rebuild/assets/91214571/a2127c72-b0b6-48cc-b4f9-acef89343046)
Из-за этого свойства сильно вытягиваются картинки. Если убрать его, то картинки не будут вытягиваться и станут в один уровень. Изначально галерея выглядит так:
![image](https://github.com/DevMentorship/paravina-rebuild/assets/91214571/04417f98-f530-4198-acff-be8d327ccfe1)

2023-06-09 03:14 UTC, oiva-terho commented on src/components/Gallery/Gallery.module.css
> +  height: 340px;
Gallery works, but photos are stretched to fixed width-height ratio on mobiles (both firefox dev tools and iOS 15). 
![image](https://github.com/DevMentorship/paravina-rebuild/assets/108938295/5f7f4142-df39-4104-b1de-5caedc53f1a0)

![bs_realios_Mobile_iPhone 13-15 0](https://github.com/DevMentorship/paravina-rebuild/assets/108938295/b58d6dee-820a-4861-86df-2c49b1ce10dd)

2023-06-09 09:00 UTC, andrey-kudinov requested changes
Круто получилось!
<img width="837" alt="image" src="https://github.com/DevMentorship/paravina-rebuild/assets/64890665/eff9a767-0b92-4108-af97-9f6453333831">
Немного растянута фотография на промежуточном разрешение
Так же немного растянуты фотографии в слайдере
Поправь пж

2023-06-10 13:04 UTC, merged