added component button
DevMentorship/paravina-rebuild pull request #35
Opened 2023-06-06 14:50 UTC by kozurasergj

2023-06-08 13:43 UTC, Grec88 approved these changes

2023-06-08 13:43 UTC, Grec88 commented on src/components/Button/Button.tsx
> +      )}
Возможно, здесь ,для лучшей читаемости кода, лучше использовать такую запись:       
 className={cn(styles.button, type === 'primary' && styles.primary,
          type === 'secondary' && styles.secondary, className)}

2023-06-08 16:53 UTC, DmitriyAvgustinovich approved these changes

2023-06-09 02:47 UTC, oiva-terho approved these changes

2023-06-09 08:55 UTC, andrey-kudinov requested changes
Круто получилось!
Сделай пж чтобы primary всегда была дефолтная, если нет пропса type
А secondary только если явно передается type="secondary"

2023-06-10 09:47 UTC, andrey-kudinov approved these changes

2023-06-10 09:47 UTC, merged