added button CALL in header
DevMentorship/paravina-rebuild pull request #36
Opened 2023-06-06 15:35 UTC by kozurasergj

2023-06-08 13:33 UTC, pontificust reviewed
Работа выглядит очень хорошо. Но есть комментарии по поводу медиа-запросов.

2023-06-08 13:33 UTC, pontificust commented on src/components/Header/Header.module.css
> +}
Эти медиа-запросы можно объединить, так код будет выглядеть лучше.

2023-06-08 13:33 UTC, pontificust commented on src/components/Header/Header.module.css
Так же можно уменьшить количество медиа-запросов до трех, так как это, по моему мнению, может сделать код лучше.

2023-06-08 16:54 UTC, DmitriyAvgustinovich approved these changes

2023-06-09 02:41 UTC, oiva-terho approved these changes

2023-06-09 08:52 UTC, andrey-kudinov requested changes
Хорошо сделано!
Есть несколько моментов которые нужно поправить
- посмотри пж комментарии и внеси исправления в соответсвии с ними
- сделай пж кнопку Позвонить как кнопку и пусть она будет самая правая

2023-06-09 11:04 UTC, merged