up-date background-image
DevMentorship/paravina-rebuild pull request #37
Opened 2023-06-07 09:00 UTC by kozurasergj

2023-06-08 13:17 UTC, pontificust approved these changes
Работа выглядит хорошо!

2023-06-08 15:45 UTC, DmitriyAvgustinovich commented
Хорошая работа!

2023-06-08 16:52 UTC, DmitriyAvgustinovich approved these changes

2023-06-09 02:35 UTC, oiva-terho commented
Looks weird on iOS 15. Photo is zoomed and is not fixed. Check screenshot in Jira, please.

2023-06-09 03:57 UTC, oiva-terho requested changes, later dismissed
Looks weird on iOS 15. Photo is zoomed and is not fixed. 
![bs_realios_Mobile_iPhone 13 Pro-15 0](https://github.com/DevMentorship/paravina-rebuild/assets/108938295/4c8236e7-910a-4dfe-94c0-9f75ebf55c05)

2023-06-09 08:46 UTC, andrey-kudinov requested changes
Десктоп выглядит отлично!)
Пофикси пж мобильную версию

2023-06-09 12:51 UTC, andrey-kudinov approved these changes

2023-06-10 11:21 UTC, merged